// Bundles server/rules.ts (+ gdd.js, data, services) into api/_lib/rules.mjs for Vercel functions.
import { build } from 'esbuild'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)))
const stub = path.join(root, 'server/supabaseStub.ts')

await build({
  entryPoints: [path.join(root, 'server/rules.ts')],
  outfile: path.join(root, 'api/_lib/rules.mjs'),
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node20',
  logLevel: 'warning',
  banner: { js: '// GENERATED by server/build.mjs from server/rules.ts -- do not edit. Run: pnpm build:server' },
  plugins: [{
    name: 'stub-browser-supabase',
    setup(b) { b.onResolve({ filter: /\/supabase$/ }, args => (args.importer.includes(`${path.sep}src${path.sep}`) ? { path: stub } : undefined)) },
  }],
})
console.log('api/_lib/rules.mjs built')
