// GENERATED BY MAGI-TECH ENGINE
export const enchantmentData = {
  "caster": {
    "ENCH-LORE-STN": {
      "id": "ENCH-LORE-STN",
      "name": "LoreStone Enchanted",
      "effect": "Increase Spell Class",
      "tiers": [
        0.25,
        0.5,
        0.5,
        1,
        1.25,
        2,
        3.25,
        4,
        5
      ]
    }, 
    "ENCH-LORE-HRT": {
      "id": "ENCH-LORE-HRT",
      "name": "LoreHeart Enchanted",
      "effect": "Increase Base SC and Base AC",
      "sc_pct_min": 0.25,
      "sc_pct_max": 3.75,
      "ac_pct_min": 0.25,
      "ac_pct_max": 5
    },
    "ENCH-TRUE-RTE": {
      "id": "ENCH-TRUE-RTE",
      "name": "True-Rite Enchanted",
      "effect": "Increase Hit Chance and Decrease Enemy WIS",
      "hit_pct_min": 0.75,
      "hit_pct_max": 7.5,
      "enemy_wis_debuff_pct_min": 2,
      "enemy_wis_debuff_pct_max": 7.5
    },
    "ENCH-MIND-RTE": {
      "id": "ENCH-MIND-RTE",
      "name": "Mindrite Enchanted",
      "effect": "Increase INT",
      "tiers": [
        1.25,
        1.875,
        2.5,
        3.125,
        3.75,
        5,
        7.5,
        10,
        12.5
      ]
    },
    "ENCH-SANG-HRT": {
      "id": "ENCH-SANG-HRT",
      "name": "Sanguine-Heart Enchanted",
      "effect": "Increase VIT and Base SC",
      "vit_pct_min": 0.6,
      "vit_pct_max": 6.25,
      "sc_pct_min": 0.1,
      "sc_pct_max": 2.5
    }
  },
  "fighter": {
    "ENCH-WAR-STN": {
      "id": "ENCH-WAR-STN",
      "name": "WarStone Enchanted",
      "effect": "Increase Weapon Class",
      "tiers": [
        0.25,
        0.5,
        0.75,
        1.25,
        1.75,
        2.5,
        3.25,
        4,
        5
      ]
    },
    "ENCH-WAR-HRT": {
      "id": "ENCH-WAR-HRT",
      "name": "WarHeart Enchanted",
      "effect": "Increase Base WC and Base AC",
      "wc_pct_min": 0.25,
      "wc_pct_max": 3.75,
      "ac_pct_min": 0.25,
      "ac_pct_max": 5
    },
    "ENCH-TRUE-LTE": {
      "id": "ENCH-TRUE-LTE",
      "name": "True-Lite Enchanted",
      "effect": "Increase Hit Chance and Decrease Enemy DEX",
      "hit_pct_min": 0.75,
      "hit_pct_max": 7.5,
      "enemy_dex_debuff_pct_min": 2,
      "enemy_dex_debuff_pct_max": 7.5
    },
    "ENCH-IGHT-RTE": {
      "id": "ENCH-IGHT-RTE",
      "name": "Mightrite Enchanted",
      "effect": "Increase DEX",
      "tiers": [
        1.25,
        1.875,
        2.5,
        3.125,
        3.75,
        5,
        7.5,
        10,
        12.5
      ]
    },
    "ENCH-JUGG-EYE": {
      "id": "ENCH-JUGG-EYE",
      "name": "Juggernaut's Eye Enchanted",
      "effect": "Increase VIT and Base WC",
      "vit_pct_min": 0.6,
      "vit_pct_max": 6.25,
      "wc_pct_min": 0.1,
      "wc_pct_max": 2.5
    }
  },
  "support": {
    "ENCH-OBSD-ENT": {
      "id": "ENCH-OBSD-ENT",
      "name": "Obsidian Enchanted",
      "effect": "Increase Armor Class",
      "tiers": [
        0.25,
        0.5,
        0.75,
        1.25,
        1.75,
        2.5,
        3.25,
        4,
        5
      ]
    },
    "ENCH-SPKE-ENT": {
      "id": "ENCH-SPKE-ENT",
      "name": "Spike-Core's Enchanted",
      "effect": "Increase Crit",
      "tiers": [
        0.25,
        0.625,
        1.25,
        1.875,
        2.5,
        3.125,
        3.75,
        4.375,
        5
      ]
    },
    "ENCH-TRUE-ENT": {
      "id": "ENCH-TRUE-ENT",
      "name": "True-Core's Enchanted",
      "effect": "Increase Hit",
      "tiers": [
        0.75,
        1.5,
        2.25,
        3,
        3.75,
        4.5,
        5.25,
        6.25,
        7.5
      ]
    },
    "ENCH-VITL-ENT": {
      "id": "ENCH-VITL-ENT",
      "name": "Vital-Core's Enchanted",
      "effect": "Increase Vitality",
      "tiers": [
        1.25,
        1.875,
        2.5,
        3.125,
        3.75,
        5,
        7.5,
        10,
        12.5
      ]
    },
    "ENCH-BLOD-ENT": {
      "id": "ENCH-BLOD-ENT",
      "name": "Blood-Core's Enchanted",
      "effect": "Steal Enemy Health",
      "tiers": [
        1,
        1.5,
        2.25,
        3.75,
        6.25,
        10,
        12.5,
        15,
        18.75
      ]
    }
  },
  "logic": {
    "generation_rules": [
      {
        "qm_min": 0.75,
        "qm_max": 0.99,
        "count_min": 0,
        "count_max": 1
      },
      {
        "qm_min": 1,
        "qm_max": 1.24,
        "count_min": 1,
        "count_max": 2
      },
      {
        "qm_min": 1.25,
        "qm_max": 1.49,
        "count_min": 2,
        "count_max": 3
      },
      {
        "qm_min": 1.5,
        "qm_max": 1.5,
        "count_min": 4,
        "count_max": 4
      }
    ]
  }
};
